APIで遊んでみるでエラー発生 >>> Question.objects.all() Traceback (most recent call last):   File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute     return self.cursor.execute(sql, params)   File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute     return Database.Cursor.execute(self, query, params) sqlite3.OperationalError: no such column: polls_question.question_text
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 263, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/kotaro_makita/PycharmProjects/pythonProject/training_Django/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: polls_question.question_text